[project]
name = "first-steps-lang-stack"
version = "0.1.0"
description = "Projeto inicial com uv"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain[ollama,openai]>=1.2.12",
    "rich>=14.3.3",
]

[project.scripts]
first-steps-lang-stack = "first_steps_lang_stack:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
